# Generated by Django 5.2.1 on 2025-06-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='hot_score',
            field=models.FloatField(default=0, verbose_name='热门分数'),
        ),
    ]
